name: tests-payments

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      STRIPE_KEY: ${{ secrets.STRIPE_KEY }}
    steps:
      - uses: actions/checkout@v2
      - run: cd payments && yarn install && yarn test:ci
