name: tests-payments

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: create env file
        run: |
          touch .env
          echo STRIPE_KEY=${{ secrets.STRIPE_KEY}} >> .env
      - run: cd payments && yarn install && yarn test:ci
